spring:
  application:
    name: notifications-service

  config:
    import: optional:configserver:http://localhost:8888 # Параметры подключения к Config Server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: host.docker.internal
        health-check-interval: 10s
        health-check-timeout: 5s
        health-check-critical-timeout: 30m

    config:
      fail-fast: true

server:
  port: 8086



#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8085/realms/bank-realm
#
#      client:
#        registration:
#          notifications-service:
#            provider: keycloak
#            client-id: notifications-service
#            client-secret: S6Go9yKeRwksV47vydTv6R9izMSBFzJM
#            authorization-grant-type: client_credentials
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8085/realms/bank-realm


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#bank:
#  accounts-service:
#    base-url: http://localhost:8081
#
#logging:
#  level:
#    root: INFO
#    org.springframework.webflux.function.server: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2.client: DEBUG
#    org.springframework.security.oauth2.core: DEBUG